
from docx import Document
from datetime import datetime
import io

def generate_docx(name, age, gender, symptoms, physical_activity, exposure, smoking, hrv):
    doc = Document()
    doc.add_heading('AMAL Radiology Report', 0)
    doc.add_paragraph(f'Date: {datetime.today().strftime("%Y-%m-%d")}')
    doc.add_paragraph(f'Patient Name: {name}')
    doc.add_paragraph(f'Age: {age}   Gender: {gender}')
    doc.add_heading('Clinical Information', level=1)
    doc.add_paragraph(f'Symptoms: {symptoms or "N/A"}')
    doc.add_paragraph(f'Physical Activity: {physical_activity}')
    doc.add_paragraph(f'Exposure: {exposure or "N/A"}')
    doc.add_paragraph(f'Smoking History: {smoking}')
    doc.add_paragraph(f'Heart Rate Variability: {hrv or "N/A"}')
    doc.add_heading('AI Diagnosis Summary', level=1)
    doc.add_paragraph('Chest X‑ray suggests consolidation in the bilateral lower zones — consistent with Pneumonia.')
    doc.add_heading('Recommendations', level=1)
    doc.add_paragraph('- Correlate with CBC and CRP labs.')
    doc.add_paragraph('- Consider antibiotic therapy and clinical review in 5–7 days.')
    doc.add_paragraph('- Repeat chest X‑ray after 1 week.')
    doc.add_paragraph('\n*Generated by AMAL – Not for final clinical decision.*')
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
